### ISSUE TITLE
UIView Events Forwards

### ISSUE THREAD

**Issue by loretoparisi** [guilhermearaujo/GUITabPagerViewController#1]
The base class GUITabPagerViewController UIViewController does not forwards UIViewController display events:

-(void)viewDidAppear:(BOOL)animated;
-(void)viewDidDisappear:(BOOL)animated;

etc.

**Comment by guilhermearaujo** [comment]
The default return value for `- (BOOL)shouldAutomaticallyForwardAppearanceMethods` is `YES`. Since the class does not override this method, the events are automatically forwarded.
This is what I understand from [the documentation](https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/CreatingCustomContainerViewControllers/CreatingCustomContainerViewControllers.html#//apple_ref/doc/uid/TP40007457-CH18-SW14).

**Comment by loretoparisi** [comment]
thanks I will check it out

**Comment by litoarias** [comment]
For what the instantiate view controllers pass for life cycle it's necessary create property of view controller and instantiate view controller and return in method viewControllerAtIndex:, for more information you can see http://stackoverflow.com/questions/27086747/how-do-i-add-multiple-viewcontrollers-to-my-uipageviewcontroller
