### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by sergey-zhuravel** [guilhermearaujo/GUITabPagerViewController#2]
1. If I have three tabs, and run the application on the iPhone 6 or iPhone 6+, the tabs are on the left side, not in the center. Or stretch the tabs on the width of the screen. So it will be more beautiful ;)
   ![ios simulator screen shot iphone6](https://cloud.githubusercontent.com/assets/7910769/6479688/1a92229a-c252-11e4-857d-edc8563810fc.png)
2. When I ViewController is tied to his NavigationController, the tabs are raised up and hide behind NavigationBar.
   ![ios simulator screen shot](https://cloud.githubusercontent.com/assets/7910769/6479772/58c22884-c253-11e4-80e1-d8eb2c021d9d.png)
   thank you ;)

**Comment by guilhermearaujo** [comment]
Check the build https://github.com/guilhermearaujo/GUITabPagerViewController/commit/7cbed10d402699ebf30129c8ea0a3f44288f956c to see if it solves your alignment issue.
I opted for centering the tabs without changing their widths. I may try later another branch increasing their width to see which looks better.

As for the insets with the translucent navigation bar, I am yet to think how to fix that. If you do have some time (more than I do), a pull request will be appreciated.

**Comment by Urkman** [comment]
There are some problems related to this:
Take a look at my fork, there are some of them solved:
https://github.com/Urkman/GUITabPagerViewController

You can solve your problem, by disabling "Under Top Bars" for your ViewController...

**Comment by Urkman** [comment]
And also call [self reloadData] is viewDidAppear, because in viewDidLoad the frames are not calculated...

**Comment by sergey-zhuravel** [comment]
Thank guilhermearaujo, this build (7cbed10) helped me :) it would be more good to tabs stretched the width of the screen.
And also will wait corrections to navigation bar ;)

Thank you very much!

**Comment by guilhermearaujo** [comment]
Centered tabs were merged into the master branch. The view controller being extended under translucent bars has been fixed too, and `reloadData` is being called within `viewWillAppear:`.
Tabs will also be redrawn on orientation changes.

All that is available on the new release 0.0.2.

@sergio-men regarding the tabs with extended widths, I would rather not implement that feature because if a user decides to provide a `UIView` instead of an `NSString`, that could deform the views. I would not like that to happen.

In your case, what you could do is to manually create your views with a single label and adjust their width so the group of tabs match the view's width.
